### PR TITLE
Uplift for Asio 1.34 against main branch

### LINKED ISSUE #1511: Compilation breaks on asio 1.34
### Priority

High

### Area

- [ ] Data
- [x] Source
- [ ] Docker
- [x] Other

### What happened?

Edit: previous compilation errors were achieved on 4.0b3. The current ones are from 8311a011a0c5730eb8501332db79013b8d5b9d3c.

With asio 1.34, compilation errors can be encountered in several object files:

`src/CMakeFiles/otclient.dir/Unity/unity_20_cxx.cxx.o`:
```
[ 30%] Building CXX object src/CMakeFiles/otclient.dir/Unity/unity_20_cxx.cxx.o
In file included from /home/mdec/git/grepwood/otclient/src/framework/net/protocol.h:27,
                 from /home/mdec/git/grepwood/otclient/src/client/protocolgame.h:28,
                 from /home/mdec/git/grepwood/otclient/src/client/game.h:29,
                 from /home/mdec/git/grepwood/otclient/src/framework/sound/soundmanager.h:26,
                 from /home/mdec/git/grepwood/otclient/src/framework/sound/soundeffect.cpp:25,
                 from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_20_cxx.cxx:10:
/home/mdec/git/grepwood/otclient/src/framework/net/connection.h:70:74: error: ‘iterator’ in ‘class asio::ip::basic_resolver<asio::ip::tcp>’ does not name a type
   70 |     void internal_connect(const asio::ip::basic_resolver<asio::ip::tcp>::iterator& endpointIterator);
      |                                                                          ^~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/net/connection.h:72:81: error: ‘iterator’ in ‘asio::ip::tcp::resolver’ {aka ‘class asio::ip::basic_resolver<asio::ip::tcp>’} does not name a type
   72 |     void onResolve(const std::error_code& error, const asio::ip::tcp::resolver::iterator& endpointIterator);
      |                                                                                 ^~~~~~~~
```

`src/CMakeFiles/otclient.dir/Unity/unity_16_cxx.cxx.o`:
```
[ 40%] Building CXX object src/CMakeFiles/otclient.dir/Unity/unity_16_cxx.cxx.o
In file included from /home/mdec/git/grepwood/otclient/src/framework/graphics/texturemanager.cpp:35,
                 from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_16_cxx.cxx:25:
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:65:33: error: expected ‘)’ before ‘&’ token
   65 |     HttpSession(asio::io_service& service, std::string url, std::string agent,
      |                ~                ^
      |                                 )
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:91:11: error: ‘io_service’ in namespace ‘asio’ does not name a type; did you mean ‘use_service’?
   91 |     asio::io_service& m_service;
      |           ^~~~~~~~~~
      |           use_service
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:115:48: error: ‘asio::ip::resolver::iterator’ has not been declared
  115 |     void on_resolve(const std::error_code& ec, asio::ip::tcp::resolver::iterator iterator);
      |                                                ^~~~
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:107:53: error: ‘m_service’ was not declared in this scope
  107 |     asio::ssl::stream<asio::ip::tcp::socket> m_ssl{ m_service, m_context };
      |                                                     ^~~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:107:74: error: could not convert ‘{<expression error>, ((HttpSession*)this)->HttpSession::m_context}’ from ‘<brace-enclosed initializer list>’ to ‘asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >’
  107 |     asio::ssl::stream<asio::ip::tcp::socket> m_ssl{ m_service, m_context };
      |                                                                          ^
      |                                                                          |
      |                                                                          <brace-enclosed initializer list>
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:135:38: error: expected ‘)’ before ‘&’ token
  135 |     WebsocketSession(asio::io_service& service, std::string url, std::string agent,
      |                     ~                ^
      |                                      )
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:157:11: error: ‘io_service’ in namespace ‘asio’ does not name a type; did you mean ‘use_service’?
  157 |     asio::io_service& m_service;
      |           ^~~~~~~~~~
      |           use_service
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:181:48: error: ‘asio::ip::resolver::iterator’ has not been declared
  181 |     void on_resolve(const std::error_code& ec, asio::ip::tcp::resolver::iterator iterator);
      |                                                ^~~~
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:174:53: error: ‘m_service’ was not declared in this scope
  174 |     asio::ssl::stream<asio::ip::tcp::socket> m_ssl{ m_service, m_context };
      |                                                     ^~~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/net/protocolhttp.h:174:74: error: could not convert ‘{<expression error>, ((WebsocketSession*)this)->WebsocketSession::m_context}’ from ‘<brace-enclosed initializer list>’ to ‘asio::ssl::stream<asio::basic_stream_socket<asio::ip::tcp> >’
  174 |     asio::ssl::stream<asio::ip::tcp::socket> m_ssl{ m_service, m_context };
      |                                                                          ^
      |                                                                          |
      |                                                                          <brace-enclosed initializer list>
```

`src/CMakeFiles/otclient.dir/Unity/unity_6_cxx.cxx.o`:
```
[ 60%] Building CXX object src/CMakeFiles/otclient.dir/Unity/unity_6_cxx.cxx.o
In file included from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_6_cxx.cxx:19:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp: In lambda function:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:59:23: error: no matching function for call to ‘asio::basic_waitable_timer<std::chrono::_V2::steady_clock>::cancel(std::error_code&)’
   59 |         m_timer.cancel(ec);
      |         ~~~~~~~~~~~~~~^~~~
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:59:23: note: there is 1 candidate
In file included from /usr/include/asio/steady_timer.hpp:19,
                 from /usr/include/asio/basic_socket_streambuf.hpp:30,
                 from /usr/include/asio/basic_socket_iostream.hpp:24,
                 from /usr/include/asio.hpp:42,
                 from /home/mdec/git/grepwood/otclient/src/framework/proxy/proxy.h:25,
                 from /home/mdec/git/grepwood/otclient/src/framework/proxy/proxy.cpp:23,
                 from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_6_cxx.cxx:16:
/usr/include/asio/basic_waitable_timer.hpp:406:15: note: candidate 1: ‘std::size_t asio::basic_waitable_timer<Clock, WaitTraits, Executor>::cancel() [with Clock = std::chrono::_V2::steady_clock; WaitTraits = asio::wait_traits<std::chrono::_V2::steady_clock>; Executor = asio::any_io_executor; std::size_t = long unsigned int]’
  406 |   std::size_t cancel()
      |               ^~~~~~
/usr/include/asio/basic_waitable_timer.hpp:406:15: note: candidate expects 0 arguments, 1 provided
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp: In member function ‘void Proxy::check(const std::error_code&)’:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:97:13: error: ‘asio::steady_timer’ {aka ‘class asio::basic_waitable_timer<std::chrono::_V2::steady_clock>’} has no member named ‘expires_from_now’
   97 |     m_timer.expires_from_now(std::chrono::milliseconds(CHECK_INTERVAL));
      |             ^~~~~~~~~~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp: In lambda function:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:130:49: error: ‘asio::ip::basic_resolver_iterator<asio::ip::tcp>’ is not an accessible base of ‘asio::ip::basic_resolver<asio::ip::tcp>::results_type’ {aka ‘asio::ip::basic_resolver_results<asio::ip::tcp>’}
  130 |             endpoint = asio::ip::tcp::endpoint(*results);
      |                                                 ^~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:130:49: error: ‘const asio::ip::basic_resolver_entry<InternetProtocol>& asio::ip::basic_resolver_iterator<InternetProtocol>::operator*() const [with InternetProtocol = asio::ip::tcp]’ is inaccessible within this context
In file included from /usr/include/asio/ip/basic_resolver.hpp:30,
                 from /usr/include/asio.hpp:124:
/usr/include/asio/ip/basic_resolver_iterator.hpp:112:49: note: declared here
  112 |   const basic_resolver_entry<InternetProtocol>& operator*() const
      |                                                 ^~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp: In lambda function:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:356:27: error: no matching function for call to ‘asio::basic_waitable_timer<std::chrono::_V2::steady_clock>::cancel(std::error_code&)’
  356 |             m_timer.cancel(ecc);
      |             ~~~~~~~~~~~~~~^~~~~
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:356:27: note: there is 1 candidate
/usr/include/asio/basic_waitable_timer.hpp:406:15: note: candidate 1: ‘std::size_t asio::basic_waitable_timer<Clock, WaitTraits, Executor>::cancel() [with Clock = std::chrono::_V2::steady_clock; WaitTraits = asio::wait_traits<std::chrono::_V2::steady_clock>; Executor = asio::any_io_executor; std::size_t = long unsigned int]’
  406 |   std::size_t cancel()
      |               ^~~~~~
/usr/include/asio/basic_waitable_timer.hpp:406:15: note: candidate expects 0 arguments, 1 provided
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp: In member function ‘void Session::check(const std::error_code&)’:
/home/mdec/git/grepwood/otclient/src/framework/proxy/proxy_client.cpp:382:13: error: ‘asio::steady_timer’ {aka ‘class asio::basic_waitable_timer<std::chrono::_V2::steady_clock>’} has no member named ‘expires_from_now’
  382 |     m_timer.expires_from_now(std::chrono::milliseconds(CHECK_INTERVAL));
      |             ^~~~~~~~~~~~~~~~
```

`src/CMakeFiles/otclient.dir/Unity/unity_5_cxx.cxx.o`:
```
[ 30%] Building CXX object src/CMakeFiles/otclient.dir/Unity/unity_5_cxx.cxx.o
In file included from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_5_cxx.cxx:19:
/home/mdec/git/grepwood/otclient/src/framework/stdext/net.cpp: In function ‘uint32_t stdext::string_to_ip(std::string_view)’:
/home/mdec/git/grepwood/otclient/src/framework/stdext/net.cpp:37:71: error: ‘from_string’ is not a member of ‘asio::ip::address_v4’
   37 |         const asio::ip::address_v4 address_v4 = asio::ip::address_v4::from_string(string.data());
      |                                                                       ^~~~~~~~~~~
/home/mdec/git/grepwood/otclient/src/framework/stdext/net.cpp:38:74: error: ‘const class asio::ip::address_v4’ has no member named ‘to_ulong’
   38 |         return asio::detail::socket_ops::host_to_network_long(address_v4.to_ulong());
      |                                                                          ^~~~~~~~
```

`src/CMakeFiles/otclient.dir/Unity/unity_3_cxx.cxx.o`:
```
[ 36%] Building CXX object src/CMakeFiles/otclient.dir/Unity/unity_3_cxx.cxx.o
In file included from /home/mdec/git/grepwood/otclient/src/framework/net/httplogin.cpp:23,
                 from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_3_cxx.cxx:13:
/home/mdec/git/grepwood/otclient/src/framework/net/httplogin.h:25:9: warning: ‘CPPHTTPLIB_OPENSSL_SUPPORT’ redefined
   25 | #define CPPHTTPLIB_OPENSSL_SUPPORT
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
<command-line>: note: this is the location of the previous definition
In file included from /home/mdec/git/grepwood/otclient/build/src/CMakeFiles/otclient.dir/Unity/unity_3_cxx.cxx:16:
/home/mdec/git/grepwood/otclient/src/framework/net/server.cpp:27:10: fatal error: asio/io_service.hpp: Nie ma takiego pliku ani katalogu
   27 | #include <asio/io_service.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by grepwood**
# Description

Summary:
A lot of things that OTClient depends on from Asio, have become deprecated sometime in Asio. I am not sure when. These changes reflect what needs to change, in order for OTClient to work with Asio 1.34 - as this is the currently stable version at least on Gentoo.

Motivation:
I want to package OTClient for Gentoo in my overlay. As such, I need to be able to build this against my own system.

Context:
Gentoo uses Asio 1.34 as a stable version. A lot has changed since then.
- `asio::io_service` removed, replace with `asio::io_context`
- `asio::io_context::reset()` does not exist, use `asio::io_context::restart()`
- `asio::ip::tcp::resolver::query` removed completely, instead pass address and port directly to `resolver.async_resolve`
- `asio::ip::tcp::resolver::iterator` removed, use `asio::ip::tcp::resolver::results_type`
- as such you can no longer use `while (it != resolver::iterator()) socket.connect(*it++);` but instead `for (auto& entry : results) socket.connect(entry.endpoint());`
- `timer.expires_from_now(duration);` does not exist anymore, use `timer.expires_after(duration);`
- `asio::buffer_cast<T*>(buffer);` no longer exists, use native data access `buffer.data().data()`
- `asio::ip::address_v4::to_ulong()` no longer exists in Asio and for good reason because `unsigned long` is 32 bit on 32 bit and 64bit on 64 bit - that is too much to represent an IPv4 address, so instead we can use `address.to_v4().to_uint()` and `unsigned int` is better for this because it's 32 bit regardless how many bits long is your general purpose register

The same breakage eventually may surface on other Linux distributions if not already encountered, since a lot of those things were removed between Asio 1.18.0 and 1.24.0. It beggars belief how did OTClient manage to compile for this long. Maybe it uses an older version? Now it can use a newer one :)

New dependencies:
- Asio 1.34.2

### **Actual**

Try and compile OTClient against Asio 1.34.2. It should exhibit many failures described in #1511

### **Expected**

OTClient should compile and run without complaints.

## Fixes

#1511

## Type of change

Please delete options that are not relevant.

  - [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested

The client has been compiled and started. However, I don't know any server to test it against at the moment.

**Test Configuration**:

  - Operating System: Gentoo Linux, amd64

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [X] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/framework/net/connection.cpp [hunk 1]
```diff
@@ -92,10 +92,16 @@
     m_error.clear();
     m_connectCallback = connectCallback;
 
-    const asio::ip::tcp::resolver::query query(host.data(), stdext::unsafe_cast<std::string>(port));
-    m_resolver.async_resolve(query, [this](auto&& error, auto&& endpointIterator) {
-        onResolve(std::move(error), std::move(endpointIterator));
-    });
+    m_resolver.async_resolve(
+        host.data(),
```
[the remark this answers is not in the document]
Comment (grepwood) [reply src/framework/net/connection.cpp]: I've addressed this in https://github.com/mehah/otclient/pull/1512/commits/2637db64f5bf895dcb2bc999ce7d9df289a084fa

**Comment by mehah** [comment]
@grepwood 
Is this finished?

**Comment by grepwood** [comment]
No @mehah, this isn't finished yet. I'm still busy with 2 things:
- SonarQube's suggestions
- un-breaking em32 target

I'll mark it as a draft.

**Comment by grepwood** [comment]
I've reviewed the situation. Windows is stuck on 1.32.0 and these changes are not entirely backwards compatible. I'll return to this, when I have something more appropriate.
